In [1]:
import dowhy
from causalgraphicalmodels import CausalGraphicalModel
from sklearn.model_selection import train_test_split
import pandas as pd
import sys
sys.path.append("../scripts/")
from plots import plot_distribution
import warnings
warnings.filterwarnings('ignore')
from dowhy import CausalModel
from IPython.display import Image, display

In [2]:
df = pd.read_csv('/home/amon/Downloads/data.csv')

In [10]:
# dropping the column with missing values
df_na_val = df.drop(['Unnamed: 32', 'id'], axis = 1)

In [11]:
df_na_val['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [12]:
df_na_val['diagnosis'].replace('B',0,inplace=True)
df_na_val['diagnosis'].replace('M',1,inplace=True)

In [13]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(df_na_val))
print(z)

[[1.29767572 1.09706398 2.07333501 ... 2.29607613 2.75062224 1.93701461]
 [1.29767572 1.82982061 0.35363241 ... 1.0870843  0.24388967 0.28118999]
 [1.29767572 1.57988811 0.45618695 ... 1.95500035 1.152255   0.20139121]
 ...
 [1.29767572 0.70228425 2.0455738  ... 0.41406869 1.10454895 0.31840916]
 [1.29767572 1.83834103 2.33645719 ... 2.28998549 1.91908301 2.21963528]
 [0.77060855 1.80840125 1.22179204 ... 1.74506282 0.04813821 0.75120669]]


In [14]:
df_clean = df_na_val[(z < 3).all(axis=1)]

In [15]:
df_clean.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
4          1        20.29         14.34          135.10     1297.0   
5          1        12.45         15.70           82.57      477.1   
6          1        18.25         19.98          119.60     1040.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
4          0.10030           0.13280          0.1980              0.10430   
5          0.12780           0.17000          0.1578              0.08089   
6          0.09463           0.10900          0.1127              0.07400   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
1         0.1812  ...         24.99          23.41            158.8   
2         0.2069  ...         23.57          25.53            152.5   
4         0.1809  ...         22.54          16.67            152.2   
5         0.2087  ...         15.47          23.75            103.4   
6         0.1794  ...         22.88          27.66            153.2   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
4      1575.0            0.1374             0.2050           0.4000   
5       741.6            0.1791             0.5249           0.5355   
6      1606.0            0.1442             0.2576           0.3784   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
4                0.1625          0.2364                  0.07678  
5                0.1741          0.3985                  0.12440  
6                0.1932          0.3063                  0.08368  

[5 rows x 31 columns]

In [16]:
from causalnex.structure.notears import from_pandas
sm = from_pandas(df_clean)

In [14]:
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
viz = plot_structure(
    sm,
    graph_attributes={"scale": "0.5"},
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK)
Image(viz.draw(format='png'))

OSError: Warning: node 'Unnamed: 0', graph '' size too small for label
Warning: node 'diagnosis', graph '' size too small for label
Warning: node 'radius_mean', graph '' size too small for label
Warning: node 'texture_mean', graph '' size too small for label
Warning: node 'perimeter_mean', graph '' size too small for label
Warning: node 'area_mean', graph '' size too small for label
Warning: node 'smoothness_mean', graph '' size too small for label
Warning: node 'compactness_mean', graph '' size too small for label
Warning: node 'concavity_mean', graph '' size too small for label
Warning: node 'concave points_mean', graph '' size too small for label
Warning: node 'symmetry_mean', graph '' size too small for label
Warning: node 'fractal_dimension_mean', graph '' size too small for label
Warning: node 'radius_se', graph '' size too small for label
Warning: node 'texture_se', graph '' size too small for label
Warning: node 'perimeter_se', graph '' size too small for label
Warning: node 'area_se', graph '' size too small for label
Warning: node 'smoothness_se', graph '' size too small for label
Warning: node 'compactness_se', graph '' size too small for label
Warning: node 'concavity_se', graph '' size too small for label
Warning: node 'concave points_se', graph '' size too small for label
Warning: node 'symmetry_se', graph '' size too small for label
Warning: node 'fractal_dimension_se', graph '' size too small for label
Warning: node 'radius_worst', graph '' size too small for label
Warning: node 'texture_worst', graph '' size too small for label
Warning: node 'perimeter_worst', graph '' size too small for label
Warning: node 'area_worst', graph '' size too small for label
Warning: node 'smoothness_worst', graph '' size too small for label
Warning: node 'compactness_worst', graph '' size too small for label
Warning: node 'concavity_worst', graph '' size too small for label
Warning: node 'concave points_worst', graph '' size too small for label
Warning: node 'symmetry_worst', graph '' size too small for label
Warning: node 'fractal_dimension_worst', graph '' size too small for label
